### ISSUE TITLE
add units to axis ticks

### ISSUE THREAD

**Issue by edwindj** [statmine/statminer#12]
Currently the units (e.g. "%") of the variables are not used in the graph.

**Comment by djvanderlaan** [comment]
This should be done in grph.js

**Comment by djvanderlaan** [comment]
And, thinking about it, this is somewhat more complicated than I initially thought:
- % you may want to add to the tickmarks
- € you may want to add to the tickmarks (except at the front, e.g. €10 and not 10€; although some countries use the latter notation)
- Other units are better placed in the axis label (e.g. 'Energy use (kJ)')

The last option probably works for most/all unit types and is, therefore, easiest to implement.
