### ISSUE TITLE
add CBS odata provider

### ISSUE THREAD

**Issue by edwindj** [statmine/statminer#7]
Add provider for CBS odata

**Comment by edwindj** [comment]
Working on it, but has some nasty details:
- codes for periods are different from `grph.js`, therefore the codes need to be translated into valid period code on the fly and translated back when making a selection.

**Comment by djvanderlaan** [comment]
Perhaps not the cleanest solution, but supporting the StatLine period format in grph.js is probably quite simple (change a regular expression so that it not only matches `2010Q1` but also `2010KW01` etc) .

**Comment by edwindj** [comment]
You read my mind :-), just working on that

**Comment by djvanderlaan** [comment]
I think you only need to change [https://github.com/statmine/grph.js/blob/master/src/date_period.js#L29](https://github.com/statmine/grph.js/blob/master/src/date_period.js#L29) and the next line.

**Comment by edwindj** [comment]
I changed it in the cbsodata provider of StatMine (is more clean I think).
